version: 1

log_path: 'C:\Users\shini\OneDrive\ƒhƒLƒ…ƒƒ“ƒg\abitrage\'
#log_path: 'C:\Users\softbank\Documents\'
log_file: 'log.log'

markets:
 bitflyer: false
 bitflyerFX: true
 bitbank: true
 coincheck: true
 zaif: false

diff: 2000

